name: chronicles
description: "Chronicles - Write Your Journey is a diary writing app powered by AI. It offers a variety of features to enhance your journaling experience, including a To-Do List, Text-to-Speech, Speech-to-Text, and the ability to share your stories with others. Chronicles also helps you remember past emotions and make new friends, allowing you to connect and reflect in meaningful ways. Plus, there are many more features designed to help you capture every moment of your journey."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/


  fonts:
    - family: Abyssinica_SIL
      fonts:
        - asset: assets/fonts/Abyssinica_SIL/AbyssinicaSIL-Regular.ttf
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind/Hind-Regular.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf